### ISSUE TITLE
Can't open Localhost or Storybook

### ISSUE THREAD

**Issue by tommy0x** [sideshiftfi/sifi#207]
Most likely caused by BigNumber.js

<img width="475" alt="Screenshot 2023-09-12 at 11 33 57" src="https://github.com/sideshiftfi/sifi/assets/128688932/b004d2f1-a22a-4fbb-86e3-be4056f95e30">

**Comment by immutablegoblin** [comment]
This was the issue I was having last week, as least we can reproduce it elsewhere now.
