### ISSUE TITLE
Failing Foundry tests

### ISSUE THREAD

**Issue by immutablegoblin** [sideshiftfi/sifi#214]
```
Failing tests:
Encountered 1 failing test in test/foundry/UniV2LikeFacet.t.sol:UniV2LikeFacetArbitrumTest
[FAIL. Reason: Setup failed: Failed to get account for 0x000000000000000000636f6e736f6c652e6c6f67: 0x000000000000000000636f6e736f6c652e6c6f67] setUp() (gas: 0)

Encountered 1 failing test in test/foundry/WarpLink.t.sol:WarpLinkArbitrumTest
[FAIL. Reason: Setup failed: Failed to get account for 0x000000000000000000636f6e736f6c652e6c6f67: 0x000000000000000000636f6e736f6c652e6c6f67] setUp() (gas: 0)

Encountered a total of 2 failing tests, 77 tests succeeded
 ELIFECYCLE  Command failed with exit code 1.
Error: Process completed with exit code 1.
```

https://github.com/sideshiftfi/sifi/actions/runs/6170390567/job/16746588175?pr=213#step:16:426

_Originally posted by @boriskubrik in https://github.com/sideshiftfi/sifi/issues/213#issuecomment-1717300883_

**Comment by mme022** [comment]
It's failing because the foundry standard node doesn't support archive block numbers for forks. So when we change the test to a newer block number it will fail in a few days. 
We should consider using maybe alchemy rpc for fork tests.
